### ISSUE TITLE
Enhancement: Make sure splunk is running to allow indexer bundle push

### ISSUE THREAD

**Issue by ForsetiJan** [splunk/ansible-role-for-splunk#11]
When updating apps on the master (app_dest = '/etc/master-apps') we should make sure splunk is running or the 'apply indexer cluster bundle' handler will fail.

in install_apps.yml after the last handler setting (need to make sure handler has a value):
First part is unchanged, just for reference.
```
- name: "Set default restart splunk handler for all other paths (e.g. etc/auth)"
  set_fact:
    handler: "restart splunk"
  when:
    - app_dest != 'etc/shcluster/apps'
    - app_dest != 'etc/deployment-apps'
    - app_dest != 'etc/master-apps'

- name: make sure splunk is running when handler = apply indexer cluster bundle
  include: splunk_start.yml
  when: handler == "apply indexer cluster bundle"
  run_once: true
```
