### ISSUE TITLE
configure_dmc.yml breaks Cluster Manager config if DMC runs on CM

### ISSUE THREAD

**Issue by igsher** [splunk/ansible-role-for-splunk#224]
Task "Configure DMC as a IDXC member" in configure_dmc.yml  attempts to configure the node as IDXC SH even if the node is already configured as IDXC Manager

Proposed fix: 
```
- name: Configure DMC as a IDXC member
  include_tasks: configure_idxc_sh.yml
  when:
    - "'clustermanager' not in group_names"

```
