### ISSUE TITLE
Bug: Apply Indexer Cluster Bundle - Rolling restart in progress

### ISSUE THREAD

**Issue by ForsetiJan** [splunk/ansible-role-for-splunk#23]
When using the 'apply indexer cluster bundle' it can falsly be registered as changed while the return is actually a warning when a rolling restart of peers is in progress.

`changed: [<hostname>] => {"attempts": 1, "changed": true, "cmd": "/opt/splunk/bin/splunk apply cluster-bundle --answer-yes --skip-validation -auth <creds>", "delta": "0:00:01.473747", "end": "2021-02-23 14:22:13.291236", "rc": 0, "start": "2021-02-23 14:22:11.817489", "stderr": "Cannot apply (or) validate configuration settings. Rolling restart of the peers is in progress.", "stderr_lines": ["Cannot apply (or) validate configuration settings. Rolling restart of the peers is in progress."], "stdout": "\nEncountered some errors while applying the bundle.", "stdout_lines": ["", "Encountered some errors while applying the bundle."]}`

We could handle this by using changed_when on look for the string below.

```
Please run 'splunk show cluster-bundle-status' for checking the status of the applied bundle.
OK
```

**Comment by ForsetiJan** [comment]
I ran into this issue when I was deploying a full distributed environment and was pushing all sorts of stuff. 

```
- name: apply indexer cluster bundle
  shell: "{{ splunk_home }}/bin/splunk apply cluster-bundle --answer-yes --skip-validation -auth {{ splunk_auth }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: apply_cluster_result
  no_log: true
  changed_when:
    - apply_cluster_result.stderr == "OK"
  failed_when:
    - '"Cannot apply (or) validate configuration settings" in apply_cluster_result.stderr'
  when: "'clustermaster' in group_names"
```

The more elegant solution would be to do the same things as we did with the SHC. But I was come to a situation where I am calling the handler directly.
