### ISSUE TITLE
Bug: Slight tab issue with roles/splunk/meta/main.yml (breaking commit)

### ISSUE THREAD

**Issue by JacobPEvans** [splunk/ansible-role-for-splunk#33]
In commit https://github.com/splunk/ansible-role-for-splunk/commit/94177ac2d21daf6bdc5329d388a9feb62be6715b, the following lines (among others) were added to `roles/splunk/meta/main.yml`:

```
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - xenial
        - bionic
      - name: Debian
        versions:
        - jessie
        - stretch
```

The following lines have two extra spaces that need deleted:
```
      - name: Debian
        versions:
```

This is the error when attempting to run a playbook without deleting the extra lines:
```
/etc/ansible/ansible-role-for-splunk/playbooks$ ansible-playbook splunk_install_or_upgrade.yml -C
ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/etc/ansible/ansible-role-for-splunk/roles/splunk/meta/main.yml': line 19, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        - bionic
      - name: Debian
      ^ here
```
      
Thank you for all of your hard work @mason-splunk ! I really appreciate it, and I'm sure many others do too.
