### ISSUE TITLE
Enhancement: Download logic and checksums

### ISSUE THREAD

**Issue by mason-splunk** [splunk/ansible-role-for-splunk#37]
**Use Case**
I want to deploy different versions of Splunk to different hosts in the same Ansible play, but not perform unnecessary downloads if there is already a local copy of the package available.

**Current Implementation**
```
- name: "Download Splunk {{ splunk_install_type }} package"
  get_url:
    url: "{{ splunk_package_url }}"
    dest: "{{ splunk_package_path }}/{{ splunk_file }}"
  delegate_to: localhost
  register: download_result
  retries: 3
  delay: 10
  until: download_result is success
  run_once: true
```
`run_once: true` would be undesirable as the play would fail if we did not have a copy of the other package already available locally. The role does not currently cleanup old tarballs post-installation from the default path of the user's home directory. 

**Suggested Implementation**

1. Remove `run_once: true` from the download task
2. Before the download task, check if the desired tarball file has already been downloaded locally via stat.
3. If the desired tarball does not exist locally, download it.
2. If the desired tarball file exists locally, check for an existing local `.sha512` hash file for the tarball.
3. If a local `.sha512` file does not exist locally, download it.
2. Compare the SHA-512 hash of the local tarball to the expected hash in the `.sha512` file.
3. If they do not match, remove the existing tarball file and download it again.
4. Compare the hash values again to ensure that they are the same. 
5. If the hashes are the same, proceed. 
6. If the hashes are still not the same (this should not happen) then we should fail the play.
