### ISSUE TITLE
configure_apps.yml does not support a git repo where there is multiple apps

### ISSUE THREAD

**Issue by Jalkar** [splunk/ansible-role-for-splunk#49]
On my gitlab, i've a repo name `splunk_apps` it contains all the apps for the same "project"!
```
- app_1
- app_2
- ...
```

May be i've missed something in my configuration but it does not seems possible to install only app_1 on a server and app_2 on a second

For me the issue lies in the task `Download defined Git repos to local Ansible host`

```
    - name: Download defined Git repos to local Ansible host
      git:
        accept_hostkey: true
        repo: "{{ item.git_server | default(git_server) }}/{{ item.git_project | default(git_project) }}/{{ item.name }}"
        version: "{{ item.git_version | default(git_version) }}"
        dest: "{{ git_local_clone_path }}{{ ansible_nodename }}/{{ item.name }}"
        key_file: "{{ git_key }}"
        force: true
      loop: "{{ git_apps }}"
      delegate_to: localhost
      changed_when: false
      check_mode: false
```

it's looping on the param `git_apps` and is expecting each of them to be a standalone git repo. For me each standalone repo should be configured by the param `git_project` only

Did I miss something ?  May be we can add the 2 possilities with a new parameter `git_multiple_app_per_repo`

**Comment by mason-splunk** [comment]
Possible implementation: Within git_apps vars, have an optional variable where the user can list out the specific folders within the repository that they would like deployed (default to all). 

Notes: 
- The installation path would likely need to be configurable at the folder level as well
- Still need to accommodate different handlers as well
- Need to evaluate further if this change would break the rsync deployment method
- This feature may need to be added at the same time as https://github.com/splunk/ansible-role-for-splunk/issues/48

**Comment by Jalkar** [comment]
We tend to use 1 git repo for all roles. This is to simplified the dev process & avoid duplicates or confusion (i can see you props.conf)

On example is : 
- an app with sourcetype info
- an app with inputs script
- an app with dashboards

Some of them will need to be deployed to a HF and the other to a single instance. 

we tend to have all the app on the same level (some times in a subfolder `splunk_apps` or directly on the root dir of the git repo

**Comment by ForsetiJan** [comment]
I resolved this challenge by creating a new task called install_multi_app.yml.
It will still take the git_apps variable to run call configure_apps.yml

The determine_handler.yml task is the following:


```
- name: sync the apps repo
  include_tasks: configure_apps.yml

- name: "Synchronize  {{ splunk_home }}/{{ splunk_app_deploy_path }}/{{ item.app_name }} to {{ splunk_home }}/{{ splunk_app_deploy_path }}/"
  shell:
    cmd: "rsync --delete --checksum --recursive --prune-empty-dirs --itemize-changes --no-owner --no-group --no-times {{ splunk_home }}/{{ splunk_app_deploy_path }}/{{ item.app_name }}/* {{ splunk_home }}/{{ splunk_app_deploy_path }}/"
  become: true
  become_user: "{{ splunk_nix_user }}"
  loop: "{{ splunk_apps }}"
  notify: "{{ handler }}"

- name: Ensure correct permissions are set
  file:
    path: "{{ splunk_home }}/{{ splunk_app_deploy_path }}/"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    recurse: true
  become: true

- name: remove the temporary app folders
  file:
    state: absent
    path: "{{ splunk_home }}/{{ splunk_app_deploy_path }}/{{ item.app_name }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  loop: "{{ splunk_apps }}"
```
