### ISSUE TITLE
Enhancement: Add support for splunk.secret to be passed as a variable

### ISSUE THREAD

**Issue by chrisbalmer** [splunk/ansible-role-for-splunk#50]
I'd like to be able to pass the splunk.secret as a variable instead of a file so it can be pulled from a secret storage (i.e. HashiCorp Vault, 1Password, etc).

**Comment by shparker1977** [comment]
You can also do this with the builtin ansible copy module:

```
- name: Push the secrets file
  tags: install
  copy:
    content: '{{ splunk_secret' }}'
    dest: '{{ splunk_home }}/etc/auth/splunk.secret'
  notify:
    - restart splunk
  ```
