### ISSUE TITLE
Issue : main.yml is reloading systemctl even if we use init.d

### ISSUE THREAD

**Issue by Jalkar** [splunk/ansible-role-for-splunk#57]
May be i've done something wrong on my box, but for me if I use init.d i should not see a trigger on systemctl daemon reload

solution trigger the reload only if we are not using initd
```yaml
- name: reload systemctl daemon
  systemd:
    daemon_reload: true
  become: true
  when: not splunk_use_initd
```
