### ISSUE TITLE
Feature: Renaming the Splunk groups with a prefix

### ISSUE THREAD

**Issue by schneewe** [splunk/ansible-role-for-splunk#65]
I have a feature request (can make a PR too) to rename the groups in the inventory file (and tasks respectively) to a more splunk name, to prefix it with splunk_ 

I had a discussion with a customer and he had a good point. You can have multiple host in an inventory which are not related to splunk. As this is a role and you can have multiple of them, group names should not be that generic like "full" or "search", due to inventories are not role dependent.

**Comment by mason-splunk** [comment]
This is a good suggestion. We can implement or if you want it sooner, feel free to PR.

**Comment by schneewe** [comment]
I will do it, thank you.

**Comment by schneewe** [comment]
I'm not sure what you mean. So, just having the current groups nested under a splunk group and limit a playbook run with the splunk group?

**Comment by mason-splunk** [comment]
Yeah, like this:

```
all:
  children:

    splunk:
      children:
      
        full:
          children:

            licensemaster:
              hosts:
                my-lm-host:

        uf:
          children:

            east_coast:
              hosts:
                someforwarder

    some_other_application:
      children:
      ...
```
