### ISSUE TITLE
example yaml playbooks do not pass ansible lint in vscode. 

### ISSUE THREAD

**Issue by bayeslearner** [splunk/ansible-role-for-splunk#93]
the extra "-" in splunk_install_or_upgrade.yml  for example.   Also ansible supports include_role and task_from.  Not sure I understand why the convoluted way to call a task from a role.  

```
---
# Example playbook to perform either a splunk installation or upgrade
- hosts:
    - all
  roles:
    - ../roles/splunk
  serial: 50
  vars:
    - deployment_task: check_splunk.yml

```
