### ISSUE TITLE
useradd appears to fail on CentOS 7 - "useradd: invalid home directory 'auto_determined'"

### ISSUE THREAD

**Issue by graememeyer** [splunk/ansible-role-for-splunk#94]
ansible-role-for-splunk fails to install Splunk for me on a CentOS 7 box with the error: ""

I'm using Vagrant to spin up the CentOS 7 box, so should be relatively easy to repro.

``` Vagrantfile
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  # config.ssh.insert_key = false
  # config.ssh.private_key_path = "/home/graeme/.ssh/id_rsa"

  config.vm.network "public_network", ip: "192.168.0.100"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./ansible-role-for-splunk-backup/playbooks/splunk_install_or_upgrade.yml"
    ansible.extra_vars = "./ansible-role-for-splunk-backup/environments/development/group_vars/all.yml"
    ansible.inventory_path = "/etc/ansible/hosts"
    ansible.limit = "all"
    end
end
```

environments\development\inventory.yml
```yml
---
all:
  children:

    # uf: # Note that you can nest additional groups under here to use with group_vars
    #   hosts:
    #     my_first_uf:
    #     my_second_uf:

    full:
      children:
        # hf:
        #   hosts:
        #     some_hf:

        search:
          hosts:
            192.168.0.100
```

environments\development\group_vars\all.yml
``` yaml
---
splunk_uri_lm: https://192.168.0.100:8089
ansible_user: vagrant
ansible_ssh_private_key_file: /home/graeme/vagrant/splunk/.vagrant/machines/default/virtualbox/private_key
git_server: ssh://git@mygithost:1234
git_key: ~/.ssh/my-git-key
splunk_admin_username: administrator
splunk_admin_password: testinglol
```

Terminal output extract:
``` 
TASK [../roles/splunk : Check if Splunk is installed] ******************************************************************
ok: [192.168.0.100]

TASK [../roles/splunk : Install Splunk if not installed] ***************************************************************
included: /home/graeme/vagrant/splunk/ansible-role-for-splunk-backup/roles/splunk/tasks/install_splunk.yml for 192.168.0.100

TASK [../roles/splunk : Add nix splunk group] **************************************************************************
ok: [192.168.0.100]

TASK [../roles/splunk : Add nix splunk user] ***************************************************************************
fatal: [192.168.0.100]: FAILED! => {"changed": false, "msg": "useradd: invalid home directory 'auto_determined'\n", "name": "splunk", "rc": 3}

PLAY RECAP *************************************************************************************************************
192.168.0.100              : ok=8    changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
```

Detailed extract from the debug output:
```
<192.168.0.100> (1, b'\r\n{"msg": "useradd: invalid home directory \'auto_determined\'\\n", "failed": true, "rc": 3, "name": "splunk", "invocation": {"module_args": {"comment": null, "ssh_key_bits": 0, "update_password": "always", "non_unique": false, "force": false, "skeleton": null, "create_home": true, "password_lock": null, "ssh_key_passphrase": null, "uid": null, "home": "auto_determined", "append": true, "ssh_key_type": "rsa", "ssh_key_comment": "ansible-generated on localhost.localdomain", "group": null, "system": false, "state": "present", "role": null, "hidden": null, "local": null, "authorization": null, "profile": null, "shell": "/bin/bash", "expires": null, "ssh_key_file": null, "groups": ["splunk"], "move_home": false, "password": null, "name": "splunk", "seuser": null, "remove": false, "login_class": null, "generate_ssh_key": null}}}\r\n', b'Shared connection to 192.168.0.100 closed.\r\n')
<192.168.0.100> Failed to connect to the host via ssh: Shared connection to 192.168.0.100 closed.
<192.168.0.100> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.0.100> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/graeme/vagrant/splunk/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o ControlPath=/home/graeme/.ansible/cp/095f9ea864 192.168.0.100 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1629794650.6224759-196759785565184/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.0.100> (0, b'', b'')
fatal: [192.168.0.100]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "append": true,
            "authorization": null,
            "comment": null,
            "create_home": true,
            "expires": null,
            "force": false,
            "generate_ssh_key": null,
            "group": null,
            "groups": [
                "splunk"
            ],
            "hidden": null,
            "home": "auto_determined",
            "local": null,
            "login_class": null,
            "move_home": false,
            "name": "splunk",
            "non_unique": false,
            "password": null,
            "password_lock": null,
            "profile": null,
            "remove": false,
            "role": null,
            "seuser": null,
            "shell": "/bin/bash",
            "skeleton": null,
            "ssh_key_bits": 0,
            "ssh_key_comment": "ansible-generated on localhost.localdomain",
            "ssh_key_file": null,
            "ssh_key_passphrase": null,
            "ssh_key_type": "rsa",
            "state": "present",
            "system": false,
            "uid": null,
            "update_password": "always"
        }
    },
    "msg": "useradd: invalid home directory 'auto_determined'\n",
    "name": "splunk",
    "rc": 3
}

PLAY RECAP *************************************************************************************************************
192.168.0.100              : ok=8    changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
```
